### ISSUE TITLE
Purge takes several minutes to complete

### ISSUE THREAD

**Issue by DanaEpp** [FabienLavocat/vsts-tasks#2]
Love the tool. Thank you for providing it.

One thing I notice is that it takes north of 3 minutes for this task to complete. However, I can see the change affected usually within a few seconds. 

Why does it take so long to complete? Is Unpublish-AzureRmCdnEndpointContent really taking that long when its running in ServiceProvider context?

Any way to speed it up?

**Comment by FabienLavocat** [comment]
Thanks a lot, I’m glad you like the tool.
The reason why it appears to be slow is because Azure needs to clean up the CDN in all the different locations across the globe. And it might seems pretty fast if you test manually because the CDN location closest to you might have been cleaned up already.

One way to make it “faster” virtually could be to run the tool asynchronously and just ignore the result. But I don’t even know if it is possible...
Another way could be to trigger an Azure Function outside of the scope and ignore the result as well...
